default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: ongraph
  password: ongraph
  host: <%= ENV['DATABASE_HOST'] %>
  database: app_development

test:
  <<: *default
  username: ongraph
  password: ongraph
  host: <%= ENV['DATABASE_HOST'] %>
  database: app_test

production:
  <<: *default
  database: app_production
  username: ongraph
  password: ongraphgit branch -M main